#!/usr/bin/env bash
# Install Nginx on Ubuntu to listen on port 80
# Serve a "Hello World" page
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a youtube video
sudo sed -i '24i\       rewrite ^/redirect_me http://psalmseins01.tech permanent;' /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
