#!/usr/bin/env bash
# Output the contents of `/etc/passwd`
# Output only the username, user id, and user home directory path

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
