#!/usr/bin/env bash
# List the content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

lst=$(ls)
for i in $lst; do
	echo "$i" | cut -d '-' -f2
done
